### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by tonyennis** [keenbrowne/flask-pbj#2]
What's the preferred way to install this?

**Comment by keenbrowne** [comment]
pip install git+https://github.com/keenbrowne/flask-pbj.git

You should then be able to from flask_pbj import api, json, protobuf
I never got around to pushing this to pypi.

Also note that I haven't tested this library with more recent versions of flask. The setup.py has a hard dependency on protobuf 2.5, I also haven't tested protobuf 2.6.1 but I expect it should work.

**Comment by tonyennis** [comment]
Installed, thanks!

**Comment by keenbrowne** [comment]
I just tested with a newer version of flask/protobuf on ubuntu. It's working for me. I imported like so: 
from flask.ext.pbj import api, json, protobuf 
and then I decorated a route like in the sample.

Hope you find this extension useful :)
